// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Context;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(PuzzlesDbContext))]
    [Migration("20240921201616_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("server.Models.MatrixEntity", b =>
                {
                    b.Property<int>("MatrixId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MatrixId"));

                    b.Property<int>("Columns")
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CreateBy");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateDate");

                    b.Property<string>("ModifyBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ModifyBy");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ModifyDate");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Rows")
                        .HasColumnType("int");

                    b.Property<string>("SerializedMatrix")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MatrixId");

                    b.ToTable("dbo_matrix", (string)null);

                    b.HasData(
                        new
                        {
                            MatrixId = 1,
                            Columns = 5,
                            CreateBy = "EF-SEED",
                            CreateDate = new DateTime(2024, 9, 21, 14, 16, 16, 41, DateTimeKind.Local).AddTicks(9),
                            ModifyBy = "EF-SEED",
                            ModifyDate = new DateTime(2024, 9, 21, 14, 16, 16, 41, DateTimeKind.Local).AddTicks(60),
                            Name = "Default",
                            Rows = 5,
                            SerializedMatrix = "[[\"A\",\"B\",\"C\",\" \",\"E\"],[\" \",\"G\",\"H\",\"I\",\"J\"],[\"K\",\"L\",\" \",\"N\",\"O\"],[\"P\",\"Q\",\"R\",\"S\",\"T\"],[\"U\",\"V\",\" \",\" \",\"Y\"]]"
                        });
                });

            modelBuilder.Entity("server.Models.MatrixEntityAudit", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AuditId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("AuditDate");

                    b.Property<int>("Columns")
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CreateBy");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateDate");

                    b.Property<int>("MatrixId")
                        .HasColumnType("int");

                    b.Property<string>("ModifyBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ModifyBy");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ModifyDate");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("Note");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("Operation");

                    b.Property<int>("Rows")
                        .HasColumnType("int");

                    b.Property<string>("SerializedMatrix")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AuditId");

                    b.ToTable("audit_matrix", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
