// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Context;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(PuzzlesDbContext))]
    [Migration("20240922174554_KnightRelationUpdate")]
    partial class KnightRelationUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("server.Models.JobEntity", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("JobId"));

                    b.Property<DateTime>("CompleteDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CreateBy");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("HangfireJobId")
                        .HasColumnType("longtext");

                    b.Property<string>("ModifyBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ModifyBy");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ModifyDate");

                    b.Property<int>("Puzzle")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.ToTable("dbo_job", (string)null);
                });

            modelBuilder.Entity("server.Models.JobEntityAudit", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AuditId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("AuditDate");

                    b.Property<DateTime>("CompleteDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CreateBy");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("HangfireJobId")
                        .HasColumnType("longtext");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("ModifyBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ModifyBy");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ModifyDate");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("Note");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("Operation");

                    b.Property<int>("Puzzle")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("AuditId");

                    b.ToTable("audit_job", (string)null);
                });

            modelBuilder.Entity("server.Models.MatrixEntity", b =>
                {
                    b.Property<int>("MatrixId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MatrixId"));

                    b.Property<int>("Columns")
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CreateBy");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateDate");

                    b.Property<string>("ModifyBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ModifyBy");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ModifyDate");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Rows")
                        .HasColumnType("int");

                    b.Property<string>("SerializedMatrix")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MatrixId");

                    b.ToTable("dbo_matrix", (string)null);

                    b.HasData(
                        new
                        {
                            MatrixId = 1,
                            Columns = 5,
                            CreateBy = "EF-SEED",
                            CreateDate = new DateTime(2024, 9, 22, 11, 45, 54, 44, DateTimeKind.Local).AddTicks(9458),
                            ModifyBy = "EF-SEED",
                            ModifyDate = new DateTime(2024, 9, 22, 11, 45, 54, 44, DateTimeKind.Local).AddTicks(9501),
                            Name = "Default",
                            Rows = 5,
                            SerializedMatrix = "[[\"A\",\"B\",\"C\",\" \",\"E\"],[\" \",\"G\",\"H\",\"I\",\"J\"],[\"K\",\"L\",\" \",\"N\",\"O\"],[\"P\",\"Q\",\"R\",\"S\",\"T\"],[\"U\",\"V\",\" \",\" \",\"Y\"]]"
                        });
                });

            modelBuilder.Entity("server.Models.MatrixEntityAudit", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AuditId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("AuditDate");

                    b.Property<int>("Columns")
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CreateBy");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateDate");

                    b.Property<int>("MatrixId")
                        .HasColumnType("int");

                    b.Property<string>("ModifyBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ModifyBy");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ModifyDate");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("Note");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("Operation");

                    b.Property<int>("Rows")
                        .HasColumnType("int");

                    b.Property<string>("SerializedMatrix")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AuditId");

                    b.ToTable("audit_matrix", (string)null);
                });

            modelBuilder.Entity("server.Models.PuzzleKnightMovesEntity", b =>
                {
                    b.Property<int>("PuzzleKnightMovesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PuzzleKnightMovesId"));

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CreateBy");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateDate");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("MatrixId")
                        .HasColumnType("int");

                    b.Property<string>("ModifyBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ModifyBy");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ModifyDate");

                    b.Property<long>("UniquePathsCount")
                        .HasColumnType("bigint");

                    b.HasKey("PuzzleKnightMovesId");

                    b.HasIndex("JobId");

                    b.HasIndex("MatrixId");

                    b.ToTable("dbo_puzzle_knightMoves", (string)null);
                });

            modelBuilder.Entity("server.Models.PuzzleKnightMovesEntityAudit", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AuditId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("AuditDate");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CreateBy");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateDate");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("MatrixId")
                        .HasColumnType("int");

                    b.Property<string>("ModifyBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ModifyBy");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ModifyDate");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("Note");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("Operation");

                    b.Property<int>("PuzzleKnightMovesId")
                        .HasColumnType("int");

                    b.Property<long>("UniquePathsCount")
                        .HasColumnType("bigint");

                    b.HasKey("AuditId");

                    b.ToTable("audit_puzzle_knightMoves", (string)null);
                });

            modelBuilder.Entity("server.Models.PuzzleKnightMovesEntity", b =>
                {
                    b.HasOne("server.Models.JobEntity", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.MatrixEntity", "Matrix")
                        .WithMany()
                        .HasForeignKey("MatrixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Matrix");
                });
#pragma warning restore 612, 618
        }
    }
}
